name: FV1 Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: FV Simple JavaScript Actions
        id: fvgreet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Frederic
      - name: FV Log Greeting Time
        run: echo "${{ step.fvgreet.outputs.time }}"
