name: FV1 Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: FV List Files
        run: |
          pwd
          ls -a
      - name: FV Checkout
        uses: actions/checkout@v1
      - name: FV List Files AFTER checkout
        run: |
          pwd
          ls -a
      - name: FV Simple JavaScript Actions
        id: fvgreet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Frederic
      - name: FV Log Greeting Time
        run: echo "${{ steps.fvgreet.outputs.time }}"
