name: FV5 Actions Workflow

on: [push, pull_request]

jobs:
  fv-run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: FV List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # not sure...git clone git@github:$GITHUB_REPOSITORY
          # not sure... git checkout GITHUB_SHA
      - name: FV Checkout
        uses: actions/checkout@v1
      - name: FV List Files AFTER checkout
        run: |
          pwd
          ls -a
      - name: FV Simple JavaScript Actions
        id: fvgreet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Frederic
      - name: FV Log Greeting Time
        run: echo "${{ steps.fvgreet.outputs.time }}"
